import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const itemWidth = (width - 30) / 2;

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#f9f9f9',
    marginBottom: 10,
  },
  itemContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  itemInfo: {
    flex: 1,
    justifyContent: 'space-between',
  },
  image: {
    width: 100,
    height: 100,
    marginRight: 10,
  },
  categoryName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: '#333',
  },
  buttonContainer: {
    marginBottom: 10, 
    width: '100%', 
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 10,
  },
  itemContainer1: {
    marginBottom: 10,
  },
  input: {
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    backgroundColor: 'white',
  },
  registerText: {
    color: 'blue',
    marginTop: 20,
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  status: {
    fontSize: 14,
    color: 'black',
    marginBottom: 5,
  },
  description: {
    flex: 1,
    fontSize: 13,
    color: 'black',
    fontWeight: 'bold',
    marginBottom: 5,
    marginTop: 5,
  },
  infoContainer: {
    backgroundColor: 'white',
    flex: 0,
  },
  favoriteContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
  },
  photo: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 20,
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    alignSelf: 'center',  
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    alignSelf: 'center',  
  },
  birthDate: {
    fontSize: 16,
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    alignSelf: 'center',  
  },
  errorText: {
    fontSize: 18,
    color: 'red',
  },
  picker: {
    width: '100%',
    height: 50,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 15,
  },
  purchaseContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,  
    marginLeft: 10,
    marginRight: 10,  
    backgroundColor: 'white',
    borderRadius: 10,
  },
  offerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  value: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'green',
  },
  discount: {
    fontSize: 14,
    color: 'red',
  },
  forgotPassword: {
    marginTop: 15,
    color: 'blue',
    textDecorationLine: 'underline',
  },
  buttonContainer: {
    marginVertical: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f0f0f0',
  },
  logo: {
    width: 100,
    height: 40,
    resizeMode: 'contain',
  },
  menuButton: {
    padding: 10,
  },
  menu: {
    position: 'absolute',
    top: 60,
    right: 10,
    backgroundColor: 'white',
    borderRadius: 5,
    elevation: 5,
    zIndex: 1000,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
    backgroundColor: '#f0f0f0',
  },
  categoryItem: {
    width: itemWidth,
    marginHorizontal: 5,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: 'hidden',
  },
  categoryImage: {
    width: '100%',
    height: 150,
    resizeMode: 'cover',
  },
  categoryName: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 10,
    color: '#333',
  },
  categoryDescription: {
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingBottom: 10,
    color: '#666',
  },
  username: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  email: {
    fontSize: 16,
    marginBottom: 10,
    textAlign: 'center',
  },
  birthDate: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  buttonContainer: {
    marginTop: 20,
  },
  productItem: {
    width: itemWidth,
    marginVertical: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  productName: {
    fontSize: 18,
    fontWeight: 'bold'
  },
  productDescription: {
    fontSize: 14,
    color: '#666',
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
  },
});
